(() => {
'use strict';
const bank=window.GRE_BANK, pairs=bank.pairs, byId=new Map(pairs.map(p=>[p.id,p])), KEY='gre-pair-demo-v1';
const $=id=>document.getElementById(id);
let state={version:1,bank:bank.id,attempts:0,correct:0,review:[],session:null}, storageOK=true;
try { const saved=JSON.parse(localStorage.getItem(KEY)); if(saved?.version===1 && saved.bank===bank.id && Array.isArray(saved.review)) state=saved; } catch { storageOK=false; }
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;} if(!storageOK)$('storage-note').textContent='浏览器存储不可用；本次可以练习，关闭后进度可能丢失。';}
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const edgeKey=(a,b)=>[a,b].sort().join('|');
const edges=new Set(pairs.map(p=>edgeKey(...p.words)));
const allWords=[...new Set(pairs.flatMap(p=>p.words))];
function optionsFor(pair){const options=[...pair.words];for(const word of shuffle(allWords)){if(options.includes(word)||options.some(w=>edges.has(edgeKey(word,w))))continue;options.push(word);if(options.length===6)break;}if(options.length!==6)throw Error('无法生成六个选项');return shuffle(options);}
function show(id){for(const page of ['setup','quiz','summary'])$(page).hidden=page!==id;}
function setup(){show('setup');$('attempts').textContent=state.attempts;$('accuracy').textContent=state.attempts?Math.round(state.correct/state.attempts*100)+'%':'—';$('review-count').textContent=state.review.length;$('resume').hidden=!state.session||state.session.index>=state.session.questions.length;$('bank-info').textContent=`${pairs.length} 组词对 · ${allWords.length} 个词 / 短语 · 已合并重复词对`;$('start').textContent=`开始 ${$('count').value} 题 →`;save();}
function start(){const pool=$('mode').value==='review'?pairs.filter(p=>state.review.includes(p.id)):pairs;if(!pool.length){$('setup-message').textContent='目前没有待复习词对，先来一轮随机练习吧。';return;}const chosen=shuffle(pool).slice(0,Number($('count').value));state.session={index:0,questions:chosen.map(p=>({id:p.id,options:optionsFor(p),selected:[],stage:'select',note:'',result:null,rating:null}))};$('setup-message').textContent='';save();render();}
function current(){return state.session.questions[state.session.index];}
function render(){const session=state.session;if(session.index>=session.questions.length){summary();return;}show('quiz');const q=current(),p=byId.get(q.id);$('position').textContent=`第 ${session.index+1} / ${session.questions.length} 题`;$('progress').style.width=`${session.index/session.questions.length*100}%`;$('options').replaceChildren();q.options.forEach((word,i)=>{const button=document.createElement('button');button.className='word';button.setAttribute('aria-pressed',String(q.selected.includes(word)));const letter=document.createElement('span');letter.className='letter';letter.textContent='ABCDEF'[i];const text=document.createElement('span');text.textContent=word;button.append(letter,text);button.disabled=q.stage!=='select';if(q.stage==='answer'){if(p.words.includes(word))button.classList.add('correct');else if(q.selected.includes(word))button.classList.add('wrong');}button.addEventListener('click',()=>{if(q.selected.includes(word))q.selected=q.selected.filter(w=>w!==word);else if(q.selected.length<2)q.selected.push(word);save();render();});$('options').append(button);});$('selection').textContent=`已选 ${q.selected.length} / 2`;$('check').hidden=q.stage!=='select';$('check').disabled=q.selected.length!==2;$('recall').hidden=q.stage!=='recall';$('answer').hidden=q.stage!=='answer';$('feedback').textContent=q.result?'配对正确！接下来回忆它们的意思。':'这次配对未命中词表。先解释你选的词，再对照答案。';$('feedback').className='feedback'+(q.result?'':' incorrect');$('paraphrase').value=q.note;if(q.stage==='answer')definitions(p,q);}
function definitions(p,q){$('definitions').replaceChildren();const title=document.createElement('h3');title.textContent=`词表配对：${p.words.join(' ↔ ')}`;$('definitions').append(title);p.words.forEach((w,i)=>{const div=document.createElement('div');div.className='definition';const strong=document.createElement('strong');strong.textContent=w;const text=document.createElement('p');text.textContent=p.meanings[i];div.append(strong,text);$('definitions').append(div);});const common=document.createElement('p');common.className='common';common.textContent='共同含义：'+p.common;$('definitions').append(common);if(q.note){const note=document.createElement('p');note.className='muted';note.textContent='你的复述：'+q.note;$('definitions').append(note);}}
function check(){const q=current();if(q.stage!=='select'||q.selected.length!==2)return;const p=byId.get(q.id);q.result=p.words.every(w=>q.selected.includes(w));q.stage='recall';state.attempts++;if(q.result)state.correct++;else addReview(q.id);save();render();$('paraphrase').focus();}
function addReview(id){if(!state.review.includes(id))state.review.push(id);}
function rate(rating){const q=current();if(q.stage!=='answer')return;q.rating=rating;if(rating==='again')addReview(q.id);else if(q.result)state.review=state.review.filter(id=>id!==q.id);state.session.index++;save();render();$('question-title').focus();}
function summary(){show('summary');const questions=state.session.questions;const correct=questions.filter(q=>q.result).length;$('summary-text').textContent=`完成 ${questions.length} 题，配对正确 ${correct} 题。待复习词对共 ${state.review.length} 组。`;$('summary-list').replaceChildren();for(const q of questions){const p=byId.get(q.id),div=document.createElement('div');div.className='summary-row';const strong=document.createElement('strong');strong.textContent=p.words.join(' ↔ ');const text=document.createElement('p');text.textContent=`${q.result?'配对正确':'配对错误'} · ${q.rating==='again'?'含义还不熟':'含义已复述'}${state.review.includes(q.id)?' · 已加入复习':''}`;div.append(strong,text);$('summary-list').append(div);}}
$('start').addEventListener('click',start);$('count').addEventListener('change',()=>{$('start').textContent=`开始 ${$('count').value} 题 →`;});$('resume').addEventListener('click',render);$('exit').addEventListener('click',()=>{save();setup();});$('check').addEventListener('click',check);$('paraphrase').addEventListener('input',()=>{current().note=$('paraphrase').value;save();});$('reveal').addEventListener('click',()=>{current().stage='answer';save();render();});document.querySelectorAll('[data-rating]').forEach(b=>b.addEventListener('click',()=>rate(b.dataset.rating)));$('again').addEventListener('click',start);$('home').addEventListener('click',setup);setup();
})();
